# Generated by Django 4.1.1 on 2022-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
