# Generated by Django 4.1.1 on 2022-10-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_country_material_year'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='owner',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='materials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.material'),
        ),
    ]
