# Generated by Django 4.1.1 on 2022-10-19 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_material_country'),
        ('favorites', '0003_alter_favorite_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
    ]
