# Generated by Django 4.1.1 on 2022-10-18 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['mp4'], message='file must be mp3')]),
        ),
    ]
