# Generated by Django 4.1.1 on 2022-10-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_country_material_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='country',
        ),
    ]
